In [ ]:
# Trader Performance vs Market Sentiment Analysis

## Objective
# To analyze how market sentiment (Fear/Greed) affects trader behavior and performance using Hyperliquid trading data.

working

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sentiment = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\power bi\\data science ]\\fear_greed_index.csv")
trades = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\power bi\\data science ]\\historical_data (1).csv")

sentiment.head()
trades.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [4]:
sentiment['date'] = pd.to_datetime(sentiment['date'], errors='coerce')

# sirf date part
sentiment['date'] = sentiment['date'].dt.date

sentiment.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [6]:
trades.rename(columns={
    'account': 'account',
    'closed pnl': 'closedPnL',
    'side': 'side',
    'leverage': 'leverage'
}, inplace=True)

In [7]:
merged = pd.merge(trades, sentiment, on='date', how='inner')

merged.head()

KeyError: 'date'

In [8]:
trades['timestamp ist'] = pd.to_datetime(trades['timestamp ist'], dayfirst=True, errors='coerce')

trades['date'] = trades['timestamp ist'].dt.date

trades.head()

KeyError: 'timestamp ist'